---
- name: Volumes which have capacity more than the threshold
  hosts: {{inventory_hostname}}
  connection: local
  vars:
    array_ip: "{{array_ip}}"
    user: "{{user}}"
    password: "{{password}}"
    verifycert:  "{{verifycert}}"
    threshold_size: enter_cap(in Bytes)
  collections:
  - dellemc.powerstore
  tasks:
    - name: Get the details of the array
      info:
        array_ip: "{{array_ip}}"
        user: "{{user}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        gather_subset:
          - vol
      register: subset_result
# The set_fact fetches the names of the volumes from the subset_result(output of the previous task).
    - set_fact:
        all_volumes_names: "{{ subset_result['Volumes'] | map(attribute='name') | list }}"
    
