---
# tasks file for auth
    - name: Authenticate & retrieve cookie
      uri:
        method: GET
        headers:
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        url: https://{{inventory_hostname}}/api/rest/appliance
        validate_certs: no
      register: result
    - name: DEBUG / GOT Login INFO
      debug:
          msg: "{{ result.dell_emc_token,result.json[0].id}}"
    - name: Info of the cluster
      uri:
        method: GET
        url: https://{{inventory_hostname}}/api/rest/appliance/{{result.json[0].id}}?select=id,name,service_tag,express_service_code,model,node_count,drive_failure_tolerance_level,drive_failure_tolerance_level_l10n,nodes,ip_pool_addresses,volumes
        validate_certs: no
        follow_redirects: yes
        return_content: yes
        status_code: 200
        headers:
          cookie: "{{ result.cookies|dictsort(false)|map('join', '=')|join('; ') }}"
          dell-emc-token: "{{ result.dell_emc_token}}"
      register: appliance
    - name: DEBUG / GOT INFO
      debug:
          msg: "{{appliance.json}}"
