---
  collections:
   - dellemc.powerstore
   - name: Get the details of cluster 
     dellemc.powerstore.cluster:
       array_ip: "{{array_ip}}"
       verifycert: "{{verifycert}}"
       user: "{{user}}"
       password: "{{password}}"
       cluster_id: "0"
       state: "present"
     register: results
   - name: Print the details of cluster
     debug:
       var: results
