---
   - name: Get the details of cluster 
      hosts: localhost
      connection: local
     dellemc.powerstore.cluster:
       array_ip: "{{inventory_hostname}"
       verifycert: false
       user: "{{user}}"
       password: "{{password}}"
       cluster_id: "0"
       state: "present"
     register: results
   - name: Print the details of cluster
     debug:
       var: results
